# Phase 4
before_script:
# Print status
  - echo -e "\e[33m+------------------------+\n|   SETTING UP PROJECT   |\n+------------------------+\e[0m"
# Install gems the Docker image may not have
  - bundle install --jobs $(nproc) "${FLAGS[@]}"
# Set up the test database
  - bundle exec rake db:migrate:reset RAILS_ENV=test

test:
  script:
# Run their unit tests, return true so that even if their unit tests fail we can continue with their other tests
    - echo -e "\e[33m+------------------------------+\n|   RUNNING THEIR UNIT TESTS   |\n+------------------------------+\e[0m"
    - bundle exec rake test:units || true
